/* tslint:disable */
/* eslint-disable */
/**
 * Leaderboard API
 * Leaderboard API to get all players\' data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@leaderboard.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LeaderboardResponse,
} from '../models/index';
import {
    LeaderboardResponseFromJSON,
    LeaderboardResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class LeaderboardApi extends runtime.BaseAPI {

    /**
     * Gets all player data to display in table
     */
    async getLeaderboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardResponseFromJSON(jsonValue));
    }

    /**
     * Gets all player data to display in table
     */
    async getLeaderboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardResponse> {
        const response = await this.getLeaderboardRaw(initOverrides);
        return await response.value();
    }

}
