/* tslint:disable */
/* eslint-disable */
/**
 * Leaderboard API
 * Leaderboard API to get all players\' data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@leaderboard.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Player } from './Player';
import {
    PlayerFromJSON,
    PlayerFromJSONTyped,
    PlayerToJSON,
} from './Player';

/**
 * 
 * @export
 * @interface LeaderboardResponse
 */
export interface LeaderboardResponse {
    /**
     * List of players
     * @type {Array<Player>}
     * @memberof LeaderboardResponse
     */
    players?: Array<Player>;
}

/**
 * Check if a given object implements the LeaderboardResponse interface.
 */
export function instanceOfLeaderboardResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardResponseFromJSON(json: any): LeaderboardResponse {
    return LeaderboardResponseFromJSONTyped(json, false);
}

export function LeaderboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'players': !exists(json, 'players') ? undefined : ((json['players'] as Array<any>).map(PlayerFromJSON)),
    };
}

export function LeaderboardResponseToJSON(value?: LeaderboardResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'players': value.players === undefined ? undefined : ((value.players as Array<any>).map(PlayerToJSON)),
    };
}

